package co.com.inascol.atenea.entity;

// Generated 13/04/2010 04:01:21 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * GppEstadocivil generated by hbm2java
 */
public class GppEstadocivil implements java.io.Serializable {

	private Integer escNidestadocivil;
	private String escVestadocivil;
	private String escVusucrea;
	private Date escDfeccrea;
	private String escVusumodifica;
	private Date escDfecmodifica;

	public GppEstadocivil() {
	}

	public GppEstadocivil(String escVestadocivil, String escVusucrea,
			Date escDfeccrea) {
		this.escVestadocivil = escVestadocivil;
		this.escVusucrea = escVusucrea;
		this.escDfeccrea = escDfeccrea;
	}

	public GppEstadocivil(String escVestadocivil, String escVusucrea,
			Date escDfeccrea, String escVusumodifica, Date escDfecmodifica) {
		this.escVestadocivil = escVestadocivil;
		this.escVusucrea = escVusucrea;
		this.escDfeccrea = escDfeccrea;
		this.escVusumodifica = escVusumodifica;
		this.escDfecmodifica = escDfecmodifica;
	}

	public Integer getEscNidestadocivil() {
		return this.escNidestadocivil;
	}

	public void setEscNidestadocivil(Integer escNidestadocivil) {
		this.escNidestadocivil = escNidestadocivil;
	}

	public String getEscVestadocivil() {
		return this.escVestadocivil;
	}

	public void setEscVestadocivil(String escVestadocivil) {
		this.escVestadocivil = escVestadocivil;
	}

	public String getEscVusucrea() {
		return this.escVusucrea;
	}

	public void setEscVusucrea(String escVusucrea) {
		this.escVusucrea = escVusucrea;
	}

	public Date getEscDfeccrea() {
		return this.escDfeccrea;
	}

	public void setEscDfeccrea(Date escDfeccrea) {
		this.escDfeccrea = escDfeccrea;
	}

	public String getEscVusumodifica() {
		return this.escVusumodifica;
	}

	public void setEscVusumodifica(String escVusumodifica) {
		this.escVusumodifica = escVusumodifica;
	}

	public Date getEscDfecmodifica() {
		return this.escDfecmodifica;
	}

	public void setEscDfecmodifica(Date escDfecmodifica) {
		this.escDfecmodifica = escDfecmodifica;
	}

}
