package co.com.inascol.atenea.entity;

// Generated 13/04/2010 04:01:21 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * GppExperiencia generated by hbm2java
 */
public class GppExperiencia implements java.io.Serializable {

	private Integer expNidexplaboral;
	private String gppMunicipioMunVidmunicipio;
	private int docNcertifica1;
	private int docNcertifica2;
	private String expVnomempresa;
	private String expVtelempresa;
	private String expVnomcontacto;
	private String expVemailcontacto;
	private String expVcargo;
	private int ceqNidcargoeq;
	private Date expDfecingreso;
	private Date expDfecretiro;
	private String expVherrasw;
	private String expVfuncionlogro;
	private String expVusucrea;
	private Date expDfeccrea;
	private String expVusumodifica;
	private Date expDfecmodifica;

	public GppExperiencia() {
	}

	public GppExperiencia(String gppMunicipioMunVidmunicipio,
			int docNcertifica1, int docNcertifica2, String expVnomempresa,
			String expVcargo, int ceqNidcargoeq, Date expDfecingreso,
			String expVusucrea, Date expDfeccrea) {
		this.gppMunicipioMunVidmunicipio = gppMunicipioMunVidmunicipio;
		this.docNcertifica1 = docNcertifica1;
		this.docNcertifica2 = docNcertifica2;
		this.expVnomempresa = expVnomempresa;
		this.expVcargo = expVcargo;
		this.ceqNidcargoeq = ceqNidcargoeq;
		this.expDfecingreso = expDfecingreso;
		this.expVusucrea = expVusucrea;
		this.expDfeccrea = expDfeccrea;
	}

	public GppExperiencia(String gppMunicipioMunVidmunicipio,
			int docNcertifica1, int docNcertifica2, String expVnomempresa,
			String expVtelempresa, String expVnomcontacto,
			String expVemailcontacto, String expVcargo, int ceqNidcargoeq,
			Date expDfecingreso, Date expDfecretiro, String expVherrasw,
			String expVfuncionlogro, String expVusucrea, Date expDfeccrea,
			String expVusumodifica, Date expDfecmodifica) {
		this.gppMunicipioMunVidmunicipio = gppMunicipioMunVidmunicipio;
		this.docNcertifica1 = docNcertifica1;
		this.docNcertifica2 = docNcertifica2;
		this.expVnomempresa = expVnomempresa;
		this.expVtelempresa = expVtelempresa;
		this.expVnomcontacto = expVnomcontacto;
		this.expVemailcontacto = expVemailcontacto;
		this.expVcargo = expVcargo;
		this.ceqNidcargoeq = ceqNidcargoeq;
		this.expDfecingreso = expDfecingreso;
		this.expDfecretiro = expDfecretiro;
		this.expVherrasw = expVherrasw;
		this.expVfuncionlogro = expVfuncionlogro;
		this.expVusucrea = expVusucrea;
		this.expDfeccrea = expDfeccrea;
		this.expVusumodifica = expVusumodifica;
		this.expDfecmodifica = expDfecmodifica;
	}

	public Integer getExpNidexplaboral() {
		return this.expNidexplaboral;
	}

	public void setExpNidexplaboral(Integer expNidexplaboral) {
		this.expNidexplaboral = expNidexplaboral;
	}

	public String getGppMunicipioMunVidmunicipio() {
		return this.gppMunicipioMunVidmunicipio;
	}

	public void setGppMunicipioMunVidmunicipio(
			String gppMunicipioMunVidmunicipio) {
		this.gppMunicipioMunVidmunicipio = gppMunicipioMunVidmunicipio;
	}

	public int getDocNcertifica1() {
		return this.docNcertifica1;
	}

	public void setDocNcertifica1(int docNcertifica1) {
		this.docNcertifica1 = docNcertifica1;
	}

	public int getDocNcertifica2() {
		return this.docNcertifica2;
	}

	public void setDocNcertifica2(int docNcertifica2) {
		this.docNcertifica2 = docNcertifica2;
	}

	public String getExpVnomempresa() {
		return this.expVnomempresa;
	}

	public void setExpVnomempresa(String expVnomempresa) {
		this.expVnomempresa = expVnomempresa;
	}

	public String getExpVtelempresa() {
		return this.expVtelempresa;
	}

	public void setExpVtelempresa(String expVtelempresa) {
		this.expVtelempresa = expVtelempresa;
	}

	public String getExpVnomcontacto() {
		return this.expVnomcontacto;
	}

	public void setExpVnomcontacto(String expVnomcontacto) {
		this.expVnomcontacto = expVnomcontacto;
	}

	public String getExpVemailcontacto() {
		return this.expVemailcontacto;
	}

	public void setExpVemailcontacto(String expVemailcontacto) {
		this.expVemailcontacto = expVemailcontacto;
	}

	public String getExpVcargo() {
		return this.expVcargo;
	}

	public void setExpVcargo(String expVcargo) {
		this.expVcargo = expVcargo;
	}

	public int getCeqNidcargoeq() {
		return this.ceqNidcargoeq;
	}

	public void setCeqNidcargoeq(int ceqNidcargoeq) {
		this.ceqNidcargoeq = ceqNidcargoeq;
	}

	public Date getExpDfecingreso() {
		return this.expDfecingreso;
	}

	public void setExpDfecingreso(Date expDfecingreso) {
		this.expDfecingreso = expDfecingreso;
	}

	public Date getExpDfecretiro() {
		return this.expDfecretiro;
	}

	public void setExpDfecretiro(Date expDfecretiro) {
		this.expDfecretiro = expDfecretiro;
	}

	public String getExpVherrasw() {
		return this.expVherrasw;
	}

	public void setExpVherrasw(String expVherrasw) {
		this.expVherrasw = expVherrasw;
	}

	public String getExpVfuncionlogro() {
		return this.expVfuncionlogro;
	}

	public void setExpVfuncionlogro(String expVfuncionlogro) {
		this.expVfuncionlogro = expVfuncionlogro;
	}

	public String getExpVusucrea() {
		return this.expVusucrea;
	}

	public void setExpVusucrea(String expVusucrea) {
		this.expVusucrea = expVusucrea;
	}

	public Date getExpDfeccrea() {
		return this.expDfeccrea;
	}

	public void setExpDfeccrea(Date expDfeccrea) {
		this.expDfeccrea = expDfeccrea;
	}

	public String getExpVusumodifica() {
		return this.expVusumodifica;
	}

	public void setExpVusumodifica(String expVusumodifica) {
		this.expVusumodifica = expVusumodifica;
	}

	public Date getExpDfecmodifica() {
		return this.expDfecmodifica;
	}

	public void setExpDfecmodifica(Date expDfecmodifica) {
		this.expDfecmodifica = expDfecmodifica;
	}

}
