package co.com.inascol.atenea.entity;

// Generated 13/04/2010 04:01:21 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * GppNivelacademico generated by hbm2java
 */
public class GppNivelacademico {

	private Integer nacNidnivelac;
	private String nacVnivelac;
	private String nacVusucrea;
	private Date nacDfeccrea;
	private String nacVusumodifica;
	private Date nacDfecmodifica;

	public GppNivelacademico() {}

	public Integer getNacNidnivelac() {
		return this.nacNidnivelac;
	}

	public void setNacNidnivelac(Integer nacNidnivelac) {
		this.nacNidnivelac = nacNidnivelac;
	}

	public String getNacVnivelac() {
		return this.nacVnivelac;
	}

	public void setNacVnivelac(String nacVnivelac) {
		this.nacVnivelac = nacVnivelac;
	}

	public String getNacVusucrea() {
		return this.nacVusucrea;
	}

	public void setNacVusucrea(String nacVusucrea) {
		this.nacVusucrea = nacVusucrea;
	}

	public Date getNacDfeccrea() {
		return this.nacDfeccrea;
	}

	public void setNacDfeccrea(Date nacDfeccrea) {
		this.nacDfeccrea = nacDfeccrea;
	}

	public String getNacVusumodifica() {
		return this.nacVusumodifica;
	}

	public void setNacVusumodifica(String nacVusumodifica) {
		this.nacVusumodifica = nacVusumodifica;
	}

	public Date getNacDfecmodifica() {
		return this.nacDfecmodifica;
	}

	public void setNacDfecmodifica(Date nacDfecmodifica) {
		this.nacDfecmodifica = nacDfecmodifica;
	}
}