package co.com.inascol.atenea.entity;

// Generated 13/04/2010 04:01:21 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * GppPais generated by hbm2java
 */
public class GppPais {

	private String paiVidpais;
	private String paiVpais;
	private String paiVusucrea;
	private Date paiDfeccrea;
	private String paiVusumodifica;
	private Date paiDfecmodifica;

	public GppPais() {}

	public String getPaiVidpais() {
		return this.paiVidpais;
	}

	public void setPaiVidpais(String paiVidpais) {
		this.paiVidpais = paiVidpais;
	}

	public String getPaiVpais() {
		return this.paiVpais;
	}

	public void setPaiVpais(String paiVpais) {
		this.paiVpais = paiVpais;
	}

	public String getPaiVusucrea() {
		return this.paiVusucrea;
	}

	public void setPaiVusucrea(String paiVusucrea) {
		this.paiVusucrea = paiVusucrea;
	}

	public Date getPaiDfeccrea() {
		return this.paiDfeccrea;
	}

	public void setPaiDfeccrea(Date paiDfeccrea) {
		this.paiDfeccrea = paiDfeccrea;
	}

	public String getPaiVusumodifica() {
		return this.paiVusumodifica;
	}

	public void setPaiVusumodifica(String paiVusumodifica) {
		this.paiVusumodifica = paiVusumodifica;
	}

	public Date getPaiDfecmodifica() {
		return this.paiDfecmodifica;
	}

	public void setPaiDfecmodifica(Date paiDfecmodifica) {
		this.paiDfecmodifica = paiDfecmodifica;
	}

}
