package co.com.inascol.atenea.entity;

// Generated 13/04/2010 04:01:21 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * GppPerfilprof generated by hbm2java
 */
public class GppPerfilprof implements java.io.Serializable {

	private Integer pprNidperfilprof;
	private int peqNidperfileq;
	private int perNidpersona;
	private String pprVperfil;
	private Integer idiNididioma1;
	private Integer pprNnivelidi1;
	private Integer idiNididioma2;
	private Integer pprNnivelidi2;
	private String pprVherrasw;
	private String pprVmotorbd;
	private String pprVusucrea;
	private Date pprDfeccrea;
	private String pprVusumodifica;
	private Date pprDfecmodifica;

	public GppPerfilprof() {
	}

	public GppPerfilprof(int peqNidperfileq, int perNidpersona,
			String pprVperfil, String pprVusucrea, Date pprDfeccrea) {
		this.peqNidperfileq = peqNidperfileq;
		this.perNidpersona = perNidpersona;
		this.pprVperfil = pprVperfil;
		this.pprVusucrea = pprVusucrea;
		this.pprDfeccrea = pprDfeccrea;
	}

	public GppPerfilprof(int peqNidperfileq, int perNidpersona,
			String pprVperfil, Integer idiNididioma1, Integer pprNnivelidi1,
			Integer idiNididioma2, Integer pprNnivelidi2, String pprVherrasw,
			String pprVmotorbd, String pprVusucrea, Date pprDfeccrea,
			String pprVusumodifica, Date pprDfecmodifica) {
		this.peqNidperfileq = peqNidperfileq;
		this.perNidpersona = perNidpersona;
		this.pprVperfil = pprVperfil;
		this.idiNididioma1 = idiNididioma1;
		this.pprNnivelidi1 = pprNnivelidi1;
		this.idiNididioma2 = idiNididioma2;
		this.pprNnivelidi2 = pprNnivelidi2;
		this.pprVherrasw = pprVherrasw;
		this.pprVmotorbd = pprVmotorbd;
		this.pprVusucrea = pprVusucrea;
		this.pprDfeccrea = pprDfeccrea;
		this.pprVusumodifica = pprVusumodifica;
		this.pprDfecmodifica = pprDfecmodifica;
	}

	public Integer getPprNidperfilprof() {
		return this.pprNidperfilprof;
	}

	public void setPprNidperfilprof(Integer pprNidperfilprof) {
		this.pprNidperfilprof = pprNidperfilprof;
	}

	public int getPeqNidperfileq() {
		return this.peqNidperfileq;
	}

	public void setPeqNidperfileq(int peqNidperfileq) {
		this.peqNidperfileq = peqNidperfileq;
	}

	public int getPerNidpersona() {
		return this.perNidpersona;
	}

	public void setPerNidpersona(int perNidpersona) {
		this.perNidpersona = perNidpersona;
	}

	public String getPprVperfil() {
		return this.pprVperfil;
	}

	public void setPprVperfil(String pprVperfil) {
		this.pprVperfil = pprVperfil;
	}

	public Integer getIdiNididioma1() {
		return this.idiNididioma1;
	}

	public void setIdiNididioma1(Integer idiNididioma1) {
		this.idiNididioma1 = idiNididioma1;
	}

	public Integer getPprNnivelidi1() {
		return this.pprNnivelidi1;
	}

	public void setPprNnivelidi1(Integer pprNnivelidi1) {
		this.pprNnivelidi1 = pprNnivelidi1;
	}

	public Integer getIdiNididioma2() {
		return this.idiNididioma2;
	}

	public void setIdiNididioma2(Integer idiNididioma2) {
		this.idiNididioma2 = idiNididioma2;
	}

	public Integer getPprNnivelidi2() {
		return this.pprNnivelidi2;
	}

	public void setPprNnivelidi2(Integer pprNnivelidi2) {
		this.pprNnivelidi2 = pprNnivelidi2;
	}

	public String getPprVherrasw() {
		return this.pprVherrasw;
	}

	public void setPprVherrasw(String pprVherrasw) {
		this.pprVherrasw = pprVherrasw;
	}

	public String getPprVmotorbd() {
		return this.pprVmotorbd;
	}

	public void setPprVmotorbd(String pprVmotorbd) {
		this.pprVmotorbd = pprVmotorbd;
	}

	public String getPprVusucrea() {
		return this.pprVusucrea;
	}

	public void setPprVusucrea(String pprVusucrea) {
		this.pprVusucrea = pprVusucrea;
	}

	public Date getPprDfeccrea() {
		return this.pprDfeccrea;
	}

	public void setPprDfeccrea(Date pprDfeccrea) {
		this.pprDfeccrea = pprDfeccrea;
	}

	public String getPprVusumodifica() {
		return this.pprVusumodifica;
	}

	public void setPprVusumodifica(String pprVusumodifica) {
		this.pprVusumodifica = pprVusumodifica;
	}

	public Date getPprDfecmodifica() {
		return this.pprDfecmodifica;
	}

	public void setPprDfecmodifica(Date pprDfecmodifica) {
		this.pprDfecmodifica = pprDfecmodifica;
	}

}
