package co.com.inascol.atenea.entity;

// Generated 13/04/2010 04:01:21 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * GppRol generated by hbm2java
 */
public class GppRol implements java.io.Serializable {

	private Integer rolNidrol;
	private String rolVnombre;
	private String rolVdescripcion;
	private String rolVactivo;
	private String rolVusucrea;
	private Date rolDfeccrea;
	private String rolVusumodifica;
	private Date rolDfecmodifica;

	public GppRol() {
	}

	public GppRol(String rolVnombre, String rolVactivo, String rolVusucrea,
			Date rolDfeccrea) {
		this.rolVnombre = rolVnombre;
		this.rolVactivo = rolVactivo;
		this.rolVusucrea = rolVusucrea;
		this.rolDfeccrea = rolDfeccrea;
	}

	public GppRol(String rolVnombre, String rolVdescripcion, String rolVactivo,
			String rolVusucrea, Date rolDfeccrea, String rolVusumodifica,
			Date rolDfecmodifica) {
		this.rolVnombre = rolVnombre;
		this.rolVdescripcion = rolVdescripcion;
		this.rolVactivo = rolVactivo;
		this.rolVusucrea = rolVusucrea;
		this.rolDfeccrea = rolDfeccrea;
		this.rolVusumodifica = rolVusumodifica;
		this.rolDfecmodifica = rolDfecmodifica;
	}

	public Integer getRolNidrol() {
		return this.rolNidrol;
	}

	public void setRolNidrol(Integer rolNidrol) {
		this.rolNidrol = rolNidrol;
	}

	public String getRolVnombre() {
		return this.rolVnombre;
	}

	public void setRolVnombre(String rolVnombre) {
		this.rolVnombre = rolVnombre;
	}

	public String getRolVdescripcion() {
		return this.rolVdescripcion;
	}

	public void setRolVdescripcion(String rolVdescripcion) {
		this.rolVdescripcion = rolVdescripcion;
	}

	public String getRolVactivo() {
		return this.rolVactivo;
	}

	public void setRolVactivo(String rolVactivo) {
		this.rolVactivo = rolVactivo;
	}

	public String getRolVusucrea() {
		return this.rolVusucrea;
	}

	public void setRolVusucrea(String rolVusucrea) {
		this.rolVusucrea = rolVusucrea;
	}

	public Date getRolDfeccrea() {
		return this.rolDfeccrea;
	}

	public void setRolDfeccrea(Date rolDfeccrea) {
		this.rolDfeccrea = rolDfeccrea;
	}

	public String getRolVusumodifica() {
		return this.rolVusumodifica;
	}

	public void setRolVusumodifica(String rolVusumodifica) {
		this.rolVusumodifica = rolVusumodifica;
	}

	public Date getRolDfecmodifica() {
		return this.rolDfecmodifica;
	}

	public void setRolDfecmodifica(Date rolDfecmodifica) {
		this.rolDfecmodifica = rolDfecmodifica;
	}

}
