package co.com.inascol.atenea.entity;

// Generated 13/04/2010 04:01:21 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * GppTipoarchivo generated by hbm2java
 */
public class GppTipoarchivo {

	private Integer tarNidtipoarchivo;
	private String tarVtipoarchivo;
	private String tarVusucrea;
	private Date tarDfeccrea;
	private String tarVusumodifica;
	private Date tarDfecmodifica;

	public GppTipoarchivo() {}


	public Integer getTarNidtipoarchivo() {
		return this.tarNidtipoarchivo;
	}

	public void setTarNidtipoarchivo(Integer tarNidtipoarchivo) {
		this.tarNidtipoarchivo = tarNidtipoarchivo;
	}

	public String getTarVtipoarchivo() {
		return this.tarVtipoarchivo;
	}

	public void setTarVtipoarchivo(String tarVtipoarchivo) {
		this.tarVtipoarchivo = tarVtipoarchivo;
	}

	public String getTarVusucrea() {
		return this.tarVusucrea;
	}

	public void setTarVusucrea(String tarVusucrea) {
		this.tarVusucrea = tarVusucrea;
	}

	public Date getTarDfeccrea() {
		return this.tarDfeccrea;
	}

	public void setTarDfeccrea(Date tarDfeccrea) {
		this.tarDfeccrea = tarDfeccrea;
	}

	public String getTarVusumodifica() {
		return this.tarVusumodifica;
	}

	public void setTarVusumodifica(String tarVusumodifica) {
		this.tarVusumodifica = tarVusumodifica;
	}

	public Date getTarDfecmodifica() {
		return this.tarDfecmodifica;
	}

	public void setTarDfecmodifica(Date tarDfecmodifica) {
		this.tarDfecmodifica = tarDfecmodifica;
	}

}
