package co.com.inascol.atenea.entity;

// Generated 13/04/2010 04:01:21 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * GppUsuariorol generated by hbm2java
 */
public class GppUsuariorol {

	private GppUsuariorolId id;
	private String urlVusucrea;
	private Date urlDfeccrea;

	public GppUsuariorol() {}

	public GppUsuariorolId getId() {
		return this.id;
	}

	public void setId(GppUsuariorolId id) {
		this.id = id;
	}

	public String getUrlVusucrea() {
		return this.urlVusucrea;
	}

	public void setUrlVusucrea(String urlVusucrea) {
		this.urlVusucrea = urlVusucrea;
	}

	public Date getUrlDfeccrea() {
		return this.urlDfeccrea;
	}

	public void setUrlDfeccrea(Date urlDfeccrea) {
		this.urlDfeccrea = urlDfeccrea;
	}

}
