package co.com.inascol.atenea.entity;

// Generated 13/04/2010 04:01:21 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.List;

/**
 * GppUsuario generated by hbm2java
 */
public class GppUsuario {

	private Integer usuNidusuario;
	private String usuVnombre;
	private String usuVlogin;
	private String usuVactivo;
	private String usuVemail;
	private String usuVtelefono;
	private String usuVusucrea;
	private Date usuDfeccrea;
	private String usuVusumodifica;
	private Date usuDfecmodifica;
	private List<Object> gppRoles;
	
	public GppUsuario() {}

	public Integer getUsuNidusuario() {
		return this.usuNidusuario;
	}

	public void setUsuNidusuario(Integer usuNidusuario) {
		this.usuNidusuario = usuNidusuario;
	}

	public String getUsuVnombre() {
		return this.usuVnombre;
	}

	public void setUsuVnombre(String usuVnombre) {
		this.usuVnombre = usuVnombre;
	}

	public String getUsuVlogin() {
		return this.usuVlogin;
	}

	public void setUsuVlogin(String usuVlogin) {
		this.usuVlogin = usuVlogin;
	}

	public String getUsuVactivo() {
		return this.usuVactivo;
	}

	public void setUsuVactivo(String usuVactivo) {
		this.usuVactivo = usuVactivo;
	}

	public String getUsuVemail() {
		return this.usuVemail;
	}

	public void setUsuVemail(String usuVemail) {
		this.usuVemail = usuVemail;
	}

	public String getUsuVtelefono() {
		return this.usuVtelefono;
	}

	public void setUsuVtelefono(String usuVtelefono) {
		this.usuVtelefono = usuVtelefono;
	}

	public String getUsuVusucrea() {
		return this.usuVusucrea;
	}

	public void setUsuVusucrea(String usuVusucrea) {
		this.usuVusucrea = usuVusucrea;
	}

	public Date getUsuDfeccrea() {
		return this.usuDfeccrea;
	}

	public void setUsuDfeccrea(Date usuDfeccrea) {
		this.usuDfeccrea = usuDfeccrea;
	}

	public String getUsuVusumodifica() {
		return this.usuVusumodifica;
	}

	public void setUsuVusumodifica(String usuVusumodifica) {
		this.usuVusumodifica = usuVusumodifica;
	}

	public Date getUsuDfecmodifica() {
		return this.usuDfecmodifica;
	}

	public void setUsuDfecmodifica(Date usuDfecmodifica) {
		this.usuDfecmodifica = usuDfecmodifica;
	}

	public void setGppRoles(List<Object> gppRoles) {
		this.gppRoles = gppRoles;
	}

	public List<Object> getGppRoles() {
		return gppRoles;
	}

}
