package co.com.inascol.atenea.entity;

// Generated 13/04/2010 04:01:21 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * GppMunicipio generated by hbm2java
 */
public class GppMunicipio {

	private String munVidmunicipio;
	private String dptViddepto;
	private String munVmunicipio;
	private String munVusucrea;
	private Date munDfeccrea;
	private String munVusumodifica;
	private Date munDfecmodifica;

	public GppMunicipio() {}

	public String getMunVidmunicipio() {
		return this.munVidmunicipio;
	}

	public void setMunVidmunicipio(String munVidmunicipio) {
		this.munVidmunicipio = munVidmunicipio;
	}

	public String getDptViddepto() {
		return this.dptViddepto;
	}

	public void setDptViddepto(String dptViddepto) {
		this.dptViddepto = dptViddepto;
	}

	public String getMunVmunicipio() {
		return this.munVmunicipio;
	}

	public void setMunVmunicipio(String munVmunicipio) {
		this.munVmunicipio = munVmunicipio;
	}

	public String getMunVusucrea() {
		return this.munVusucrea;
	}

	public void setMunVusucrea(String munVusucrea) {
		this.munVusucrea = munVusucrea;
	}

	public Date getMunDfeccrea() {
		return this.munDfeccrea;
	}

	public void setMunDfeccrea(Date munDfeccrea) {
		this.munDfeccrea = munDfeccrea;
	}

	public String getMunVusumodifica() {
		return this.munVusumodifica;
	}

	public void setMunVusumodifica(String munVusumodifica) {
		this.munVusumodifica = munVusumodifica;
	}

	public Date getMunDfecmodifica() {
		return this.munDfecmodifica;
	}

	public void setMunDfecmodifica(Date munDfecmodifica) {
		this.munDfecmodifica = munDfecmodifica;
	}
}