package co.com.inascol.atenea.entity;

// Generated 13/04/2010 04:01:21 PM by Hibernate Tools 3.3.0.GA

/**
 * GppParametrizacion generated by hbm2java
 */
public class GppParametrizacion {

	private Integer parNidparam;
	private String parVnombre;
	private String parVvalor;
	private String parVdescripcion;

	public GppParametrizacion() {}

	public Integer getParNidparam() {
		return this.parNidparam;
	}

	public void setParNidparam(Integer parNidparam) {
		this.parNidparam = parNidparam;
	}

	public String getParVnombre() {
		return this.parVnombre;
	}

	public void setParVnombre(String parVnombre) {
		this.parVnombre = parVnombre;
	}

	public String getParVvalor() {
		return this.parVvalor;
	}

	public void setParVvalor(String parVvalor) {
		this.parVvalor = parVvalor;
	}

	public String getParVdescripcion() {
		return this.parVdescripcion;
	}

	public void setParVdescripcion(String parVdescripcion) {
		this.parVdescripcion = parVdescripcion;
	}

}
