package co.com.inascol.atenea.entity;

// Generated 13/04/2010 04:01:21 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * GppUsuariorol generated by hbm2java
 */
public class GppUsuariorol implements java.io.Serializable {

	private GppUsuariorolId id;
	private String urlVusucrea;
	private Date urlDfeccrea;

	public GppUsuariorol() {
	}

	public GppUsuariorol(GppUsuariorolId id, String urlVusucrea,
			Date urlDfeccrea) {
		this.id = id;
		this.urlVusucrea = urlVusucrea;
		this.urlDfeccrea = urlDfeccrea;
	}

	public GppUsuariorolId getId() {
		return this.id;
	}

	public void setId(GppUsuariorolId id) {
		this.id = id;
	}

	public String getUrlVusucrea() {
		return this.urlVusucrea;
	}

	public void setUrlVusucrea(String urlVusucrea) {
		this.urlVusucrea = urlVusucrea;
	}

	public Date getUrlDfeccrea() {
		return this.urlDfeccrea;
	}

	public void setUrlDfeccrea(Date urlDfeccrea) {
		this.urlDfeccrea = urlDfeccrea;
	}

}
